### PR TITLE
Loggly tag support and rspec testing

### PR DESCRIPTION
**Pull request by nywilken**
Resubmission of PR https://github.com/logstash-plugins/logstash-output-loggly/pull/3 with separated commit messages to statisfy the request made by @karmi

### CODE REVIEW

**Comment by nywilken** [comment]
@suyograo is there any other steps needed for getting this PR merged in?

**Comment by suyograo** [comment]
LGTM

**Comment by suyograo** [comment]
@nywilken can you create a PR with a version bump and we can release a new gem

**Comment by nywilken** [comment]
Please see my latest PR with the version bump. Thank you for merging my
changes.

**Pull request closed without merging**
