### PR TITLE
Use loggly bulk API

### PR DESCRIPTION
**Pull request by Vincent--**
See https://www.loggly.com/docs/http-bulk-endpoint/

With the bulk API and some tweaking on the number of output workers and the flush size, the speed increased by around 50 times on my setup.

### CODE REVIEW

**Comment by Vincent--** [comment]
Next steps is to implement the multi_receive(events) to support logstash 2.2.x
See https://www.elastic.co/blog/logstash-2-2-0-and-2-1-2-released
and https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html

**Comment by torrancew** [comment]
+1 here, this is a huge design flaw with the current plugin. Connections are set up/torn down for **each** event in the current model. HTTPS and Proxies only exacerbate this.

**Comment by suyograo** [comment]
@Vincent-- apologies for not moving on this PR. Can you please rebase? I can merge this then

**Comment by Vincent--** [comment]
@suyograo, done 👍

**Comment by bangonkali** [comment]
Are there any plans to merge this?

**Comment by webmat** [comment]
This has been merged and expanded upon. Published as [v4.0.0](https://rubygems.org/gems/logstash-output-loggly/versions/4.0.0).

**Pull request closed without merging**
